[package]
name = "rite-runtime"
description = "Execution runtime for Rite ceremonies"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false #TODO enable at a later time, disabled for safety

[dependencies]
rite-sdk   = { path = "../rite-sdk" }
rite-model = { path = "../rite-model" }

serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
chrono     = { workspace = true }
sha2       = { workspace = true }
base16ct   = { workspace = true }
base32ct   = { workspace = true }
base64ct   = { workspace = true }
rpassword  = "=7.5.2"

[dev-dependencies]
rite-resolver = { path = "../rite-resolver" }
tempfile = { workspace = true }

[lints]
workspace = true
