//! HTML report generation from extracted report data.

#![allow(clippy::format_push_string)]

use crate::html::escape_html;
use crate::report::config::ReportConfig;
use crate::report::data::build_report_data;
use crate::theme::THEME_CSS;
use chrono::{DateTime, Utc};
use rite_model::Ceremony;
use rite_model::transcript::ParsedTranscript;

/// Input for report generation.
pub struct ReportInput<'a> {
    /// Parsed and verified transcript.
    pub transcript: &'a ParsedTranscript,
    /// Optional ceremony definition for richer context (role names, duties).
    pub ceremony: Option<&'a Ceremony>,
    /// Report configuration (which sections to include).
    pub config: ReportConfig,
}

/// Generate an HTML ceremony report.
///
/// The generated HTML is self-contained (embedded CSS) and print-optimized.
pub fn generate_report_html(input: &ReportInput<'_>) -> String {
    let data = build_report_data(input.transcript, input.ceremony);
    let config = &input.config;
    let mut html = String::new();

    html.push_str("<!DOCTYPE html>\n<html>\n<head>\n");
    html.push_str(&format!(
        "  <title>{} \u{2014} Ceremony Report</title>\n",
        escape_html(&data.ceremony_name)
    ));
    html.push_str("  <meta charset=\"UTF-8\">\n");
    html.push_str("  <style>\n");
    html.push_str(THEME_CSS);
    html.push_str("  </style>\n");
    html.push_str("</head>\n<body>\n");

    html.push_str(&format!(
        "  <h1>{} \u{2014} Ceremony Report</h1>\n",
        escape_html(&data.ceremony_name)
    ));

    if data.dry_run {
        html.push_str("  <div class=\"dry-run-banner\">DRY RUN \u{2014} No actual cryptographic operations were performed</div>\n");
    }

    if config.show_summary {
        render_summary(&mut html, &data);
    }

    if config.show_parameters && !data.parameters.is_empty() {
        render_parameters(&mut html, &data);
    }

    if config.show_participants && !data.participants.is_empty() {
        render_participants(&mut html, &data);
    }

    if config.show_deviations && !data.deviations.is_empty() {
        render_deviations(&mut html, &data);
    }

    if config.show_artifacts && !data.artifacts.is_empty() {
        render_artifacts(&mut html, &data);
    }

    if config.show_execution_log && !data.steps.is_empty() {
        render_execution_log(&mut html, &data);
    }

    if config.show_duties
        && let Some(ceremony) = input.ceremony
        && !ceremony.after.is_empty()
    {
        html.push_str("  <h2>Post-Ceremony Duties</h2>\n");
        html.push_str("  <p class=\"duties-intro\">The following duties must be completed after the ceremony concludes.</p>\n");
        for duty in &ceremony.after {
            html.push_str(&crate::html::render_duty(duty, ceremony));
        }
        html.push('\n');
    }

    html.push_str(&format!(
        "  <div class=\"report-footer\">Generated by Rite v{}</div>\n",
        env!("CARGO_PKG_VERSION")
    ));

    html.push_str("</body>\n</html>\n");
    html
}

#[allow(clippy::arithmetic_side_effects)]
fn render_summary(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <div class=\"summary-box\">\n");
    let status_display = crate::html::capitalize_words(&data.status.replace('_', " "));
    html.push_str(&format!(
        "    <p><strong>Status:</strong> <span class=\"status-{}\">{}</span></p>\n",
        escape_html(&data.status),
        escape_html(&status_display)
    ));
    html.push_str(&format!(
        "    <p><strong>Started:</strong> {}</p>\n",
        format_datetime(&data.started_at)
    ));
    if let Some(end) = &data.completed_at {
        html.push_str(&format!(
            "    <p><strong>Completed:</strong> {}</p>\n",
            format_datetime(end)
        ));
        let duration = *end - data.started_at;
        html.push_str(&format!(
            "    <p><strong>Duration:</strong> {}</p>\n",
            format_duration(duration)
        ));
    }
    html.push_str(&format!(
        "    <p><strong>Binary Version:</strong> {}</p>\n",
        escape_html(&data.binary_version)
    ));
    if let Some(bf) = &data.binary_fingerprint {
        html.push_str(&format!(
            "    <p><strong>Binary Fingerprint:</strong> <span class=\"hash\">{}</span></p>\n",
            escape_html(bf)
        ));
    }
    html.push_str(&format!(
        "    <p><strong>Ceremony Fingerprint:</strong> <span class=\"hash\">{}</span></p>\n",
        escape_html(&data.ceremony_fingerprint)
    ));
    html.push_str(&format!(
        "    <p><strong>Transcript Fingerprint:</strong> <span class=\"hash\">{}</span></p>\n",
        escape_html(&data.transcript_fingerprint)
    ));
    html.push_str("  </div>\n\n");
}

fn render_parameters(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <h2>Parameters</h2>\n");
    html.push_str("  <div class=\"metadata\">\n");
    for (key, value) in &data.parameters {
        let display_key = crate::html::capitalize_words(&key.replace('_', " "));
        html.push_str(&format!(
            "    <p><strong>{}:</strong> {}</p>\n",
            escape_html(&display_key),
            escape_html(value)
        ));
    }
    html.push_str("  </div>\n\n");
}

fn render_participants(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <h2>Participants</h2>\n");
    html.push_str("  <ul class=\"roles\">\n");
    for p in &data.participants {
        let person_suffix = p
            .person
            .as_deref()
            .map(|person| format!(" \u{2014} {}", escape_html(person)))
            .unwrap_or_default();
        if p.display_name == p.role_id {
            html.push_str(&format!(
                "    <li><strong>{}</strong>{}</li>\n",
                escape_html(&p.role_id),
                person_suffix
            ));
        } else {
            html.push_str(&format!(
                "    <li><strong>{}</strong>{} ({})</li>\n",
                escape_html(&p.display_name),
                person_suffix,
                escape_html(&p.role_id)
            ));
        }
    }
    html.push_str("  </ul>\n\n");
}

fn render_deviations(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <div class=\"deviations\">\n");
    html.push_str("    <h3>Deviations from Procedure</h3>\n");
    html.push_str("    <ul>\n");
    for d in &data.deviations {
        let step_ref = d
            .step_id
            .as_deref()
            .map(|s| format!(" (step {s})"))
            .unwrap_or_default();
        html.push_str(&format!(
            "      <li>{}{} \u{2014} <em>{}</em></li>\n",
            escape_html(&d.reason),
            escape_html(&step_ref),
            format_datetime(&d.recorded_at)
        ));
    }
    html.push_str("    </ul>\n");
    html.push_str("  </div>\n\n");
}

fn render_artifacts(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <h2>Artifacts Produced</h2>\n");
    html.push_str("  <table>\n");
    html.push_str("    <thead>\n");
    html.push_str("      <tr>\n");
    html.push_str("        <th>File</th>\n");
    html.push_str("        <th>Source</th>\n");
    html.push_str("        <th>SHA-256 Fingerprint</th>\n");
    html.push_str("        <th>Size</th>\n");
    html.push_str("      </tr>\n");
    html.push_str("    </thead>\n");
    html.push_str("    <tbody>\n");
    for a in &data.artifacts {
        html.push_str("      <tr>\n");
        html.push_str(&format!("        <td>{}</td>\n", escape_html(&a.path)));
        html.push_str(&format!("        <td>{}</td>\n", escape_html(&a.source)));
        html.push_str(&format!(
            "        <td class=\"hash\">{}</td>\n",
            escape_html(&a.hash)
        ));
        html.push_str(&format!("        <td>{}</td>\n", format_size(a.size)));
        html.push_str("      </tr>\n");
    }
    html.push_str("    </tbody>\n");
    html.push_str("  </table>\n\n");
}

#[allow(clippy::arithmetic_side_effects)]
fn render_execution_log(html: &mut String, data: &crate::report::data::ReportData) {
    html.push_str("  <h2>Execution Log</h2>\n");
    html.push_str("  <table>\n");
    html.push_str("    <thead>\n");
    html.push_str("      <tr>\n");
    html.push_str("        <th>Step</th>\n");
    html.push_str("        <th>Action</th>\n");
    html.push_str("        <th>Role</th>\n");
    html.push_str("        <th>Started</th>\n");
    html.push_str("        <th>Duration</th>\n");
    html.push_str("        <th>Outcome</th>\n");
    html.push_str("      </tr>\n");
    html.push_str("    </thead>\n");
    html.push_str("    <tbody>\n");
    for s in &data.steps {
        let duration = s.completed_at - s.started_at;
        let role = s.role.as_deref().unwrap_or("\u{2014}");
        let status_class = match s.outcome_status.as_str() {
            "completed" => "status-completed",
            "skipped" => "status-skipped",
            _ => "",
        };
        let outcome_text = match &s.outcome_message {
            Some(msg) => format!("{}: {msg}", s.outcome_status),
            None => s.outcome_status.clone(),
        };
        html.push_str("      <tr>\n");
        html.push_str(&format!("        <td>{}</td>\n", escape_html(&s.step_id)));
        html.push_str(&format!(
            "        <td>{}</td>\n",
            escape_html(&s.action.to_string())
        ));
        html.push_str(&format!("        <td>{}</td>\n", escape_html(role)));
        html.push_str(&format!(
            "        <td>{}</td>\n",
            format_datetime(&s.started_at)
        ));
        html.push_str(&format!("        <td>{}</td>\n", format_duration(duration)));
        html.push_str(&format!(
            "        <td class=\"{status_class}\">{}</td>\n",
            escape_html(&outcome_text)
        ));
        html.push_str("      </tr>\n");
    }
    html.push_str("    </tbody>\n");
    html.push_str("  </table>\n\n");
}

fn format_datetime(dt: &DateTime<Utc>) -> String {
    dt.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}

fn format_duration(d: chrono::Duration) -> String {
    let total_secs = d.num_seconds();
    if total_secs < 1 {
        return "&lt;1s".to_string();
    }
    let hours = total_secs / 3600;
    let minutes = (total_secs % 3600) / 60;
    let seconds = total_secs % 60;
    if hours > 0 {
        format!("{hours}h {minutes}m {seconds}s")
    } else if minutes > 0 {
        format!("{minutes}m {seconds}s")
    } else {
        format!("{seconds}s")
    }
}

fn format_size(bytes: u64) -> String {
    #[allow(clippy::cast_precision_loss)]
    if bytes < 1024 {
        format!("{bytes} B")
    } else if bytes < 1024 * 1024 {
        format!("{:.1} KB", bytes as f64 / 1024.0)
    } else {
        format!("{:.1} MB", bytes as f64 / (1024.0 * 1024.0))
    }
}
