//! HTML report rendering from extracted [`ReportData`].
//!
//! Built-in renderer; produces a self-contained HTML document with the
//! shared theme CSS inlined. Template engines that want a different
//! layout consume [`ReportData`] directly via its `Serialize` impl.

#![allow(clippy::format_push_string)]

use chrono::{DateTime, Duration, Utc};

use crate::html::{capitalize_words, escape_html};
use crate::report::data::{ReportData, ReportStatus, format_duration};
use crate::theme::THEME_CSS;

/// Render a [`ReportData`] into a self-contained HTML document.
#[must_use]
pub fn generate_report_html(data: &ReportData) -> String {
    let mut html = String::new();

    html.push_str("<!DOCTYPE html>\n<html>\n<head>\n");
    html.push_str(&format!(
        "  <title>{} \u{2014} Ceremony Report</title>\n",
        escape_html(&data.ceremony_name)
    ));
    html.push_str("  <meta charset=\"UTF-8\">\n");
    html.push_str("  <style>\n");
    html.push_str(THEME_CSS);
    html.push_str("  </style>\n");
    html.push_str("</head>\n<body>\n");

    html.push_str(&format!(
        "  <h1>{} \u{2014} Ceremony Report</h1>\n",
        escape_html(&data.ceremony_name)
    ));

    render_summary(&mut html, data);

    if !data.deviations.is_empty() {
        render_deviations(&mut html, data);
    }
    if !data.artifacts.is_empty() {
        render_artifacts(&mut html, data);
    }
    if !data.steps.is_empty() {
        render_execution_log(&mut html, data);
    }

    html.push_str(&format!(
        "  <div class=\"report-footer\">Generated by Rite v{}</div>\n",
        env!("CARGO_PKG_VERSION")
    ));
    html.push_str("</body>\n</html>\n");
    html
}

fn render_summary(html: &mut String, data: &ReportData) {
    let status_slug = status_slug(data.status);
    let status_display = capitalize_words(&status_slug.replace('_', " "));
    html.push_str("  <div class=\"summary-box\">\n");
    html.push_str(&format!(
        "    <p><strong>Status:</strong> <span class=\"status-{}\">{}</span></p>\n",
        escape_html(status_slug),
        escape_html(&status_display)
    ));
    html.push_str(&format!(
        "    <p><strong>Started:</strong> {}</p>\n",
        format_datetime(&data.started_at)
    ));
    if let Some(end) = &data.completed_at {
        html.push_str(&format!(
            "    <p><strong>Completed:</strong> {}</p>\n",
            format_datetime(end)
        ));
    }
    if let Some(secs) = data.duration_seconds {
        html.push_str(&format!(
            "    <p><strong>Duration:</strong> {}</p>\n",
            format_duration(Duration::seconds(secs))
        ));
    }
    html.push_str(&format!(
        "    <p><strong>Transcript fingerprint:</strong> <code>{}</code></p>\n",
        escape_html(&data.transcript_fingerprint)
    ));
    if let Some(failure) = &data.failure {
        html.push_str(&format!(
            "    <p><strong>Failure:</strong> {} ({})</p>\n",
            escape_html(&failure.message),
            escape_html(&failure.kind),
        ));
    }
    html.push_str("  </div>\n");
}

fn render_deviations(html: &mut String, data: &ReportData) {
    html.push_str("  <h2>Deviations</h2>\n");
    html.push_str("  <table class=\"deviations\">\n");
    html.push_str("    <thead><tr><th>Recorded</th><th>Step</th><th>Note</th></tr></thead>\n");
    html.push_str("    <tbody>\n");
    for dev in &data.deviations {
        html.push_str(&format!(
            "      <tr><td>{}</td><td><code>{}</code></td><td>{}</td></tr>\n",
            format_datetime(&dev.recorded_at),
            escape_html(&dev.step_id),
            escape_html(&dev.text),
        ));
    }
    html.push_str("    </tbody>\n  </table>\n");
}

fn render_artifacts(html: &mut String, data: &ReportData) {
    html.push_str("  <h2>Artifacts</h2>\n");
    html.push_str("  <table class=\"artifacts\">\n");
    html.push_str(
        "    <thead><tr><th>Name</th><th>Step</th><th>Path</th><th>SHA-256</th></tr></thead>\n",
    );
    html.push_str("    <tbody>\n");
    for art in &data.artifacts {
        html.push_str(&format!(
            "      <tr><td>{}</td><td><code>{}</code></td><td><code>{}</code></td><td><code>{}</code></td></tr>\n",
            escape_html(&art.name),
            escape_html(&art.step_id),
            escape_html(&art.path),
            escape_html(&art.sha256),
        ));
    }
    html.push_str("    </tbody>\n  </table>\n");
}

fn render_execution_log(html: &mut String, data: &ReportData) {
    html.push_str("  <h2>Execution Log</h2>\n");
    html.push_str("  <table class=\"execution-log\">\n");
    html.push_str(
        "    <thead><tr><th>Step</th><th>Label</th><th>Role</th><th>Started</th><th>Completed</th><th>Outcome</th></tr></thead>\n",
    );
    html.push_str("    <tbody>\n");
    for step in &data.steps {
        let completed = step
            .completed_at
            .as_ref()
            .map_or_else(|| "\u{2014}".to_string(), format_datetime);
        let outcome = match &step.outcome_message {
            Some(msg) => format!("{}, {}", step.outcome_status, msg),
            None => step.outcome_status.clone(),
        };
        html.push_str(&format!(
            "      <tr><td><code>{}</code></td><td>{}</td><td><code>{}</code></td><td>{}</td><td>{}</td><td>{}</td></tr>\n",
            escape_html(&step.step_id),
            escape_html(&step.label),
            escape_html(&step.role),
            format_datetime(&step.started_at),
            completed,
            escape_html(&outcome),
        ));
    }
    html.push_str("    </tbody>\n  </table>\n");
}

fn status_slug(status: ReportStatus) -> &'static str {
    match status {
        ReportStatus::Completed => "completed",
        ReportStatus::Failed => "failed",
        ReportStatus::InProgress => "in_progress",
    }
}

fn format_datetime(dt: &DateTime<Utc>) -> String {
    dt.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}
