[package]
name = "rite-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "rite"
path = "src/main.rs"

[features]
default = ["rite-stdlib/default"]
openssl = ["rite-stdlib/openssl"]
verification = ["rite-stdlib/verification"]
attestation = ["rite-stdlib/attestation"]
crypto = ["rite-stdlib/crypto"]
pki = ["rite-stdlib/pki"]
openssl-vendored = ["rite-stdlib/openssl-vendored"]

[dependencies]
rite-model = { path = "../rite-model" }
rite-resolver = { path = "../rite-resolver" }
rite-runtime = { path = "../rite-runtime" }
rite-stdlib = { path = "../rite-stdlib", default-features = false }
clap = { workspace = true }
clap_complete = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
