//! OpenSSL backend for Rite ceremonies.
//!
//! Provides [`OpenSslBackend`], a software cryptographic backend backed by OpenSSL.
//! Keys are held in memory for the lifetime of the backend instance.
//!
//! # Capabilities
//!
//! [`OpenSslBackend`] implements the following [`rite_sdk`] traits:
//!
//! - [`KeyStoreBackend`](rite_sdk::KeyStoreBackend): key generation and import
//! - [`SignBackend`](rite_sdk::SignBackend): signing
//! - [`VerifyBackend`](rite_sdk::VerifyBackend): signature verification
//! - [`KeyTransportBackend`](rite_sdk::KeyTransportBackend): key wrapping and unwrapping
//! - [`RandomBackend`](rite_sdk::RandomBackend): random byte generation
//!
//! [`verify_signature`] works without a backend instance, so it applies to keys
//! this crate never held (a PIV card's, say). [`seal_content`] and
//! [`open_content`] are free of a backend for a different reason: content
//! encryption is not an operation any key-protection device performs, so it
//! belongs beside the backends rather than inside one.
//!
//! # Feature flags
//!
//! - `vendored`: bundle OpenSSL at build time (no system library needed). Required for
//!   air-gapped USB image builds.
//!
//! # Stability
//!
//! Internal crate. This is an implementation detail of the `rite` CLI, with no
//! stable API and no semver guarantees across releases. Build against the
//! public `rite-sdk`, `rite-model`, or `rite-resolver` crates instead.

#![warn(missing_docs)]

mod backend;
mod content;

pub use backend::{OpenSslBackend, verify_signature};
pub use content::{SealedContent, open_content, seal_content};

/// Whether this build can perform ML-DSA and ML-KEM operations.
///
/// Both arrived in OpenSSL 3.5, and the bindings for them are selected when
/// `rite-openssl` is compiled, not when it runs. A binary linked against an
/// older OpenSSL contains none of that code, so this is a property of the
/// build and cannot be recovered by inspecting the runtime library version.
///
/// Callers that can offer a useful alternative (skipping a test, warning before
/// a ceremony starts) should branch on this rather than waiting for
/// [`BackendError::UnsupportedAlgorithm`](rite_sdk::BackendError) mid-run.
pub const POST_QUANTUM_AVAILABLE: bool = cfg!(ossl350);

/// What about *this build* prevents generating keys of this algorithm.
///
/// The question belongs here rather than in a caller: which algorithms depend
/// on [`POST_QUANTUM_AVAILABLE`] is a property of the bindings this crate
/// compiles, and matching exhaustively means a new algorithm cannot be added
/// without answering it.
///
/// `None` covers both an algorithm this build can generate and one no build
/// can. Only a limitation of the binary doing the asking belongs here: a
/// caller reports it as a warning rather than a defect in the ceremony,
/// because another machine's build may run the same document.
#[must_use]
pub fn build_limitation(algorithm: rite_sdk::KeyAlgorithm) -> Option<&'static str> {
    use rite_sdk::KeyAlgorithm;
    // Matched exhaustively, so a key algorithm added to the SDK cannot skip
    // the question. Everything outside the post-quantum set is generated by
    // every build, so no build is what limits it.
    let post_quantum = matches!(
        algorithm,
        KeyAlgorithm::MlDsa44
            | KeyAlgorithm::MlDsa65
            | KeyAlgorithm::MlDsa87
            | KeyAlgorithm::MlKem512
            | KeyAlgorithm::MlKem768
            | KeyAlgorithm::MlKem1024
    );
    match algorithm {
        KeyAlgorithm::Rsa2048
        | KeyAlgorithm::Rsa4096
        | KeyAlgorithm::EcdsaP256
        | KeyAlgorithm::EcdsaP384
        | KeyAlgorithm::Ed25519
        | KeyAlgorithm::Aes128
        | KeyAlgorithm::Aes256
        | KeyAlgorithm::MlDsa44
        | KeyAlgorithm::MlDsa65
        | KeyAlgorithm::MlDsa87
        | KeyAlgorithm::MlKem512
        | KeyAlgorithm::MlKem768
        | KeyAlgorithm::MlKem1024 => {}
        _ => return None,
    }
    (post_quantum && !POST_QUANTUM_AVAILABLE)
        .then_some("needs a build linked against OpenSSL 3.5 or later, and this one is not")
}
